"""
Django settings for booking_project project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')






# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'nonpendant-profligately-tessa.ngrok-free.dev', 'coachalvarez44.com', '.onrender.com']

LOGIN_URL = '/login/'   # Or any URL you want for your login page

LOGIN_REDIRECT_URL = '/client_menu/' # or any page you want after login
LOGOUT_REDIRECT_URL = '/'  # or any page you want after logout


# Application definition

INSTALLED_APPS = [
   # 'django_q',
    'django_extensions',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookings',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    
]


STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

ROOT_URLCONF = 'booking_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR / 'bookings' / 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'booking_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use SQLite locally if running on your PC
# Detect by checking if "RUNNING_LOCALLY" env variable is set


if os.environ.get("RUNNING_LOCALLY") == "1":
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # Use Render's PostgreSQL
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
        )
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Los_Angeles'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "bookings" / "static", # Adjusted path to static files
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_IGNORE_PATTERNS = ['*.mov', '*.mp4']

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#if os.environ.get("RUNNING_LOCALLY") == "1":
    # Local dev: print emails to console
 #   EMAIL_BACKEND = 'bookings.email_backends.BrevoEmailBackend'
#else:
    # Live: send real emails via Brevo SMTP
EMAIL_BACKEND = 'bookings.email_backends.BrevoEmailBackend'
EMAIL_HOST = 'smtp-relay.brevo.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('BREVO_SMTP_KEY')
DEFAULT_FROM_EMAIL = 'Developmental Baseball <noreply@coachalvarez44.com>'

BREVO_API_KEY = os.getenv('BREVO_API_KEY')
EMAIL_RECEIVER = os.getenv('EMAIL_RECEIVER')



# Keep user logged in even after closing the browser

SESSION_EXPIRE_AT_BROWSER_CLOSE = True

TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN')
TWILIO_PHONE_NUMBER = os.getenv('TWILIO_PHONE_NUMBER')


#Q_CLUSTER = {
 
 #   'name': 'cluster44',  # just a name for the cluster
#  'workers': 2,          # number of worker processes
 #   'recycle': 500,        # auto-recycle worker after this many tasks
  #  'timeout': 60,         # max time per task
   # 'retry': 60,           # retry failed tasks after 60 sec
   # 'queue_limit': 50,     # max number of tasks in queue at once
    #'bulk': 10,            # number of tasks to process at once
  #  'orm': 'default',      # uses your default database (PostgreSQL)
#}