# Generated by Django 5.2.6 on 2025-09-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_duration_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('reason', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('client', 'date', 'start_time'), name='unique_booking_per_client_start'),
        ),
        migrations.AddConstraint(
            model_name='blockedtime',
            constraint=models.UniqueConstraint(fields=('date', 'start_time', 'end_time'), name='unique_blocked_time'),
        ),
    ]
