# Generated by Django 5.2.6 on 2025-09-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_blockedtime_booking_unique_booking_per_client_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedtime',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blockedtime',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
