# Generated by Django 5.2.6 on 2025-10-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_blockedtime_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='blockedtime',
            name='unique_blocked_time',
        ),
        migrations.AlterField(
            model_name='blockedtime',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
