# Generated by Django 5.2.6 on 2025-10-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_blockedtime_unique_blocked_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='device_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
