# Generated by Django 5.2.6 on 2025-10-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_client_device_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='sms_opt_in',
            field=models.BooleanField(default=False),
        ),
    ]
