# Generated by Django 5.2.7 on 2025-10-17 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_client_sms_opt_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='lesson_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookings.lessontype'),
        ),
        migrations.AlterField(
            model_name='lessontype',
            name='duration',
            field=models.PositiveBigIntegerField(choices=[(30, '30 Minutes'), (60, '1 Hour')]),
        ),
    ]
